# Site settings
title: Quentin Donnellan
email: quentin@qdonnellan.com
tagline: Software, Engineering & Education
description: >
  I am a software engineer deeply passionate about learning new things and helping others to the same. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.qdonnellan.com" # the base hostname & protocol for your site
github_username:  qdonnellan

# Build settings
markdown: kramdown

collections:
  projects:
    output: true
    permalink: /projects/:path/

