# Site settings
title: Quentin Donnellan
email: quentin@qdonnellan.com
description: >
  I'm a software engineer at SpiderOak. Previously I've taught high school
  Astronomy, Engineering, Physics, and Calculus. Before that I was an Aerospace
  Engineer. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://qdonnellan.github.io" # the base hostname & protocol for your site
github_username:  qdonnellan

# Build settings
markdown: kramdown
